# Generated by Django 4.0.3 on 2022-04-16 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_bait'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bait',
            name='type',
            field=models.CharField(choices=[('LB', 'Live Bait'), ('L', 'Lure'), ('S', 'Spinner'), ('P', 'Power Bait'), ('SE', 'Salmon Eggs')], default='LB', max_length=2, verbose_name='Types of Bait used'),
        ),
    ]
