# Generated by Django 4.0.3 on 2022-04-16 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_rename_bait_baiting_rename_type_baiting_kind'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Baiting',
            new_name='Bait',
        ),
        migrations.RenameField(
            model_name='bait',
            old_name='kind',
            new_name='type',
        ),
    ]
