# Generated by Django 4.0.3 on 2022-04-16 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_rename_baiting_bait_rename_kind_bait_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Location Name')),
            ],
        ),
        migrations.RemoveField(
            model_name='fish',
            name='length',
        ),
        migrations.AlterField(
            model_name='bait',
            name='type',
            field=models.CharField(choices=[('LB', 'Live Bait'), ('L', 'Lure'), ('S', 'Spinner'), ('P', 'Power Bait'), ('SE', 'Salmon Eggs')], default='LB', max_length=2, verbose_name='Types Of Bait Used'),
        ),
    ]
