# Generated by Django 4.0.3 on 2022-04-16 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_location_remove_fish_length_alter_bait_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fish',
            name='location',
        ),
        migrations.AddField(
            model_name='fish',
            name='locations',
            field=models.ManyToManyField(to='main_app.location'),
        ),
    ]
